ServerEvents.recipes(event => {
    event.remove([
        { id: "moreminecarts:minecart_with_chunk_loader" },

        { id: "computercraft:turtle_normal" },
        { id: "computercraft:turtle_normal_overlays/turtle_trans_overlay" },
        { id: "computercraft:turtle_normal_overlays/turtle_rainbow_overlay" },
        { id: "computercraft:turtle_advanced" },
        { id: "computercraft:turtle_advanced_upgrade" },
        { id: "computercraft:turtle_advanced_overlays/turtle_trans_overlay" },
        { id: "computercraft:turtle_advanced_overlays/turtle_rainbow_overlay" },

        { id: "lightmanscurrency:coinmint" },
        { id: "lightmanscurrency:gem_terminal" },
        { id: "lightmanscurrency:portable_gem_terminal" },
        { id: "lightmanscurrency:gem_terminal_swap" },
        { id: "lightmanscurrency:portable_gem_terminal_swap" },
        { id: "lightmanscurrency:slot_machine" },
        { id: "lightmanscurrency:traders/slot_machine" },
        { id: "lightmanscurrency:coin_chocolate_copper" },
        { id: "lightmanscurrency:coinpile_chocolate_copper" },
        { id: "lightmanscurrency:coinblock_chocolate_copper" },
        { id: "lightmanscurrency:coin_chocolate_iron" },
        { id: "lightmanscurrency:coinpile_chocolate_iron" },
        { id: "lightmanscurrency:coinblock_chocolate_iron" },
        { id: "lightmanscurrency:coin_chocolate_gold" },
        { id: "lightmanscurrency:coinpile_chocolate_gold" },
        { id: "lightmanscurrency:coinblock_chocolate_gold" },
        { id: "lightmanscurrency:coin_chocolate_emerald" },
        { id: "lightmanscurrency:coinpile_chocolate_emerald" },
        { id: "lightmanscurrency:coinblock_chocolate_emerald" },
        { id: "lightmanscurrency:coin_chocolate_diamond" },
        { id: "lightmanscurrency:coinpile_chocolate_diamond" },
        { id: "lightmanscurrency:coinblock_chocolate_diamond" },
        { id: "lightmanscurrency:coin_chocolate_netherite" },
        { id: "lightmanscurrency:coinpile_chocolate_netherite" },
        { id: "lightmanscurrency:coinblock_chocolate_netherite" },

        { id: "createdeco:gold_coin" },
        { id: "createdeco:pressing/coins/gold_coin" },
        { id: "createdeco:gold_coinstack" },
        { id: "createdeco:netherite_coin" },
        { id: "createdeco:pressing/coins/netherite_coin" },
        { id: "createdeco:netherite_coinstack" },
        { id: "createdeco:brass_coin" },
        { id: "createdeco:pressing/coins/brass_coin" },
        { id: "createdeco:brass_coinstack" },
        { id: "createdeco:iron_coin" },
        { id: "createdeco:pressing/coins/iron_coin" },
        { id: "createdeco:iron_coinstack" },
        { id: "createdeco:copper_coin" },
        { id: "createdeco:pressing/coins/copper_coin" },
        { id: "createdeco:copper_coinstack" },
        { id: "createdeco:industrial_iron_coin" },
        { id: "createdeco:pressing/coins/industrial_iron_coin" },
        { id: "createdeco:industrial_iron_coinstack" },
        { id: "createdeco:zinc_coin" },
        { id: "createdeco:pressing/coins/zinc_coin" },
        { id: "createdeco:zinc_coinstack" },

        { id: "scalinghealth:heart_crystal" },
        { id: "scalinghealth:heart_dust" },
        { id: "scalinghealth:power_crystal" },
        { id: "scalinghealth:bandages" },
        { id: "scalinghealth:medkit" },

        { id: "bhc:red_heart_canister" },
        { id: "bhc:yellow_heart_canister" },
        { id: "bhc:green_heart_canister" },
        { id: "bhc:blue_heart_canister" },
        { id: "bhc:soul_heart_canister" },
        { id: "bhc:canister" },
        { id: "bhc:relic_apple" },
    ]);
})