JEIEvents.hideItems(event => {
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:amathyllis", rec: "agricraft:amathyllis" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:aurigold", rec: "agricraft:aurigold" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:carbonation", rec: "agricraft:carbonation" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:cuprosia", rec: "agricraft:cuprosia" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:diamahlia", rec: "agricraft:diamahlia" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:emeryllis", rec: "agricraft:emeryllis" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:ferranium", rec: "agricraft:ferranium" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:jaslumine", rec: "agricraft:jaslumine" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:lapender", rec: "agricraft:lapender" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:nethereed", rec: "agricraft:nethereed" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:niccissus", rec: "agricraft:niccissus" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:nitor_wart", rec: "agricraft:nitor_wart" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:osmonium", rec: "agricraft:osmonium" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:petinia", rec: "agricraft:petinia" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:platiolus", rec: "agricraft:platiolus" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:plombean", rec: "agricraft:plombean" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:quartzanthemum", rec: "agricraft:quartzanthemum" } } }).weakNBT())
    event.hide(Item.of('agricraft:seed', { genes: { species: { dom: "agricraft:redstodendron", rec: "agricraft:redstodendron" } } }).weakNBT())
    event.hide("agricraft:coal_pebble")
    event.hide("agricraft:diamond_shard")
    event.hide("agricraft:emerald_shard")
    event.hide("agricraft:quartz_shard")
    event.hide("agricraft:netherite_sliver")
    event.hide("agricraft:amathyllis_petal")

    event.hide("bhc:red_heart_patch")
    event.hide("bhc:yellow_heart_patch")
    event.hide("bhc:green_heart_patch")
    event.hide("bhc:blue_heart_patch")
    event.hide("bhc:canister")
    event.hide("bhc:relic_apple")

    event.hide("computercraft:turtle_normal")
    event.hide("computercraft:turtle_advanced")

    event.hide("create:mechanical_drill")

    event.hide("create_connected:copycat_block")
    event.hide("create_connected:copycat_slab")
    event.hide("create_connected:copycat_beam")
    event.hide("create_connected:copycat_vertical_step")
    event.hide("create_connected:copycat_stairs")
    event.hide("create_connected:copycat_fence")
    event.hide("create_connected:copycat_fence_gate")
    event.hide("create_connected:copycat_wall")
    event.hide("create_connected:copycat_board")
    event.hide("create_connected:copycat_box")
    event.hide("create_connected:copycat_catwalk")

    event.hide("createdeco:gold_coin")
    event.hide("createdeco:gold_coinstack")
    event.hide("createdeco:netherite_coin")
    event.hide("createdeco:netherite_coinstack")
    event.hide("createdeco:brass_coin")
    event.hide("createdeco:brass_coinstack")
    event.hide("createdeco:iron_coin")
    event.hide("createdeco:iron_coinstack")
    event.hide("createdeco:copper_coin")
    event.hide("createdeco:copper_coinstack")
    event.hide("createdeco:industrial_iron_coin")
    event.hide("createdeco:industrial_iron_coinstack")
    event.hide("createdeco:zinc_coin")
    event.hide("createdeco:zinc_coinstack")

    event.hide("lightmanscurrency:coin_chocolate_copper")
    event.hide("lightmanscurrency:coinpile_chocolate_copper")
    event.hide("lightmanscurrency:coinblock_chocolate_copper")
    event.hide("lightmanscurrency:coin_chocolate_iron")
    event.hide("lightmanscurrency:coinpile_chocolate_iron")
    event.hide("lightmanscurrency:coinblock_chocolate_iron")
    event.hide("lightmanscurrency:coin_chocolate_gold")
    event.hide("lightmanscurrency:coinpile_chocolate_gold")
    event.hide("lightmanscurrency:coinblock_chocolate_gold")
    event.hide("lightmanscurrency:coin_chocolate_emerald")
    event.hide("lightmanscurrency:coinpile_chocolate_emerald")
    event.hide("lightmanscurrency:coinblock_chocolate_emerald")
    event.hide("lightmanscurrency:coin_chocolate_diamond")
    event.hide("lightmanscurrency:coinpile_chocolate_diamond")
    event.hide("lightmanscurrency:coinblock_chocolate_diamond")
    event.hide("lightmanscurrency:coin_chocolate_netherite")
    event.hide("lightmanscurrency:coinpile_chocolate_netherite")
    event.hide("lightmanscurrency:coinblock_chocolate_netherite")

    event.hide("minecraft:ender_chest")

    event.hide("railways:track_phantom")

    event.hide("scalinghealth:deepslate_heart_crystal_ore")
    event.hide("scalinghealth:deepslate_power_crystal_ore")
    event.hide("scalinghealth:heart_crystal_ore")
    event.hide("scalinghealth:power_crystal_ore")
    event.hide("scalinghealth:heart_crystal_shard")
    event.hide("scalinghealth:power_crystal_shard")
    event.hide("scalinghealth:heart_crystal")
    event.hide("scalinghealth:power_crystal")
    event.hide("scalinghealth:heart_dust")
    event.hide("scalinghealth:bandages")
    event.hide("scalinghealth:medkit")
    event.hide("scalinghealth:cursed_heart")
    event.hide("scalinghealth:enchanted_heart")
    event.hide("scalinghealth:chance_heart")

    event.hide("tfmg:bottle_of_battery_acid")

    event.hide("utilitix:backpack")
    event.hide("utilitix:ender_cart")
    
    event.hide("undergarden:catalyst")
})