# Use the official Node.js image based on Alpine
FROM node:21-alpine3.17

# Install basic development tools
RUN apk update && apk add --no-cache less man-db sudo git openssh zsh curl

# Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Ensure .zshrc file exists and is writable by the node user
RUN touch /home/node/.zshrc && chown node:node /home/node/.zshrc

# Set theme to agnoster
RUN sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/g' /home/node/.zshrc

# Install zsh-syntax-highlighting plugin
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-/home/node/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
RUN sed -i 's/plugins=(git)/plugins=(git zsh-syntax-highlighting)/g' /home/node/.zshrc

# Ensure default node user has access to sudo
RUN echo node ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/node \
    && chmod 0440 /etc/sudoers.d/node

# Set DEVCONTAINER environment variable to help with orientation
ENV DEVCONTAINER=true

# Change the owner of the directories to the node user
USER root
RUN chown -R node:node /usr/local/lib
RUN chown -R node:node /usr/local/bin
USER node

# Set default shell to zsh
ENV SHELL /bin/zsh

# Set custom prompt without hostname
RUN echo 'PROMPT="[%F{cyan}%n%f | %F{green}%~%f] "' >> /home/node/.zshrc

# Install packwiz
USER root
RUN curl -sSL https://github.com/packwiz/packwiz/releases/latest/download/packwiz-linux-amd64 -o /usr/local/bin/packwiz && \
    chmod +x /usr/local/bin/packwiz
USER node